testname: Speech Intelligibility Test
testId: Test_Intelligible_1
#bufferSize: 2048
bufferSize: 512
stopOnErrors: true
showButtonPreviousPage: true
remoteService: service/write.php


pages:

    - type: generic
      id: title_page
      name: Speech Intelligibility Test
      content: The next few screens will ask you to grade several audio clips, based on how clearly you can hear the speech present in those clips.
    - type: volume
      id: vol_page
      name: Volume Adjustment
      content: Please set the volume so that the sample plays loud and clear. For consistency, this volume level should not be altered once the test has begun. 
      stimulus: configs/resources/audio/mono_c1.wav
      defaultVolume: 0.5
    -
      - random   
      -    
        - type: mushra
          id: test_m3db_anechoic
          name: Listening Test
          content: Please listen to the reference. Then, grade each of the stimuli below by assessing how they compare to the reference. 
          showWaveform: true
          enableLooping: true 
          reference: configs/resources/audio/m3dB/Anechoic/p278_062_0_mc.wav
          createAnchor35: true
          createAnchor70: true
          randomize: true
          showConditionNames: false
          stimuli:
              MBCCTN: configs/resources/audio/m3dB/Anechoic/p278_062_0_ISO.wav
              OMVDR: configs/resources/audio/m3dB/Anechoic/p278_062_0_omvdr.wav
              GOMVDR: configs/resources/audio/m3dB/Anechoic/p278_062_0_mc_OMVDR.wav
              GFCIM: configs/resources/audio/m3dB/Anechoic/p278_062_0_mc_FCIM.wav
      -
        - type: mushra
          id: test_m3db_reverb
          name: Listening Test
          content: Please listen to the reference. Then, grade each of the stimuli below by assessing how they compare to the reference. 
          showWaveform: true
          enableLooping: true 
          reference: configs/resources/audio/m3dB/Reverb/p278_101_1_mc_rb.wav
          createAnchor35: true
          createAnchor70: true
          randomize: true
          showConditionNames: false
          stimuli: 
              MBCCTN: configs/resources/audio/m3dB/Reverb/p278_101_1_ISO_RB.wav
              OMVDR: configs/resources/audio/m3dB/Reverb/p278_101_1_omvdr.wav
              GOMVDR: configs/resources/audio/m3dB/Reverb/p278_101_1_OMVDR_RB.wav 
              GFCIM: configs/resources/audio/m3dB/Reverb/p278_101_1_rb_mc_FCIM_RB.wav
      -
        - type: mushra
          id: test_m6db_anechoic
          name: Listening Test
          content: Please listen to the reference. Then, grade each of the stimuli below by assessing how they compare to the reference. 
          showWaveform: true
          enableLooping: true 
          reference: configs/resources/audio/m6dB/Anechoic/p278_297_1_mc.wav
          createAnchor35: true
          createAnchor70: true
          randomize: true
          showConditionNames: false
          stimuli: 
              MBCCTN: configs/resources/audio/m6dB/Anechoic/p278_297_1_ISO.wav
              OMVDR: configs/resources/audio/m6dB/Anechoic/p278_297_1_omvdr.wav
              GOMVDR: configs/resources/audio/m6dB/Anechoic/p278_297_1_mc_OMVDR.wav
              GFCIM: configs/resources/audio/m6dB/Anechoic/p278_297_1_mc_FCIM.wav
      -
        - type: mushra
          id: test_m6db_reverb
          name: Listening Test
          content: Please listen to the reference. Then, grade each of the stimuli below by assessing how they compare to the reference. 
          showWaveform: true
          enableLooping: true 
          reference: configs/resources/audio/m6dB/Reverb/p278_326_0_mc_rb.wav
          createAnchor35: true
          createAnchor70: true
          randomize: true
          showConditionNames: false
          stimuli: 
              MBCCTN: NO RB FILE IN DATA
              OMVDR: NO RB FILE IN DATA
              GOMVDR: configs/resources/audio/m6dB/Reverb/p278_326_0_OMVDR_RB.wav
              GFCIM: configs/resources/audio/m6dB/Reverb/p278_326_0_rb_mc_FCIM_RB.wav
      -
        - type: mushra
          id: test_0db_anechoic
          name: Listening Test
          content: Please listen to the reference. Then, grade each of the stimuli below by assessing how they compare to the reference. 
          showWaveform: true
          enableLooping: true 
          reference: configs/resources/audio/0dB/Anechoic/p279_166_1_mc.wav
          createAnchor35: true
          createAnchor70: true
          randomize: true
          showConditionNames: false
          stimuli: 
              MBCCTN: configs/resources/audio/0dB/Anechoic/p279_166_1_ISO.wav
              OMVDR: configs/resources/audio/0dB/Anechoic/p279_166_1_omvdr.wav
              GOMVDR: configs/resources/audio/0dB/Anechoic/p279_166_1_mc_OMVDR.wav
              GFCIM: configs/resources/audio/0dB/Anechoic/p279_166_1_mc_FCIM.wav
      -
        - type: mushra
          id: test_0db_reverb
          name: Listening Test
          content: Please listen to the reference. Then, grade each of the stimuli below by assessing how they compare to the reference. 
          showWaveform: true
          enableLooping: true 
          reference: configs/resources/audio/0dB/Reverb/p279_196_1_mc_rb.wav
          createAnchor35: true
          createAnchor70: true
          randomize: true
          showConditionNames: false
          stimuli: 
              MBCCTN: configs/resources/audio/0dB/Reverb/p279_196_1_ISO_RB.wav
              OMVDR: configs/resources/audio/0dB/Reverb/p279_196_1_omvdr.wav
              GOMVDR: configs/resources/audio/0dB/Reverb/p279_196_1_OMVDR_RB.wav
              GFCIM: configs/resources/audio/0dB/Reverb/p279_196_1_rb_mc_FCIM_RB.wav
      -
        - type: mushra
          id: test_3db_anechoic
          name: Listening Test
          content: Please listen to the reference. Then, grade each of the stimuli below by assessing how they compare to the reference. 
          showWaveform: true
          enableLooping: true 
          reference: configs/resources/audio/3dB/Anechoic/p286_172_1_mc.wav
          createAnchor35: true
          createAnchor70: true
          randomize: true
          showConditionNames: false
          stimuli: 
              MBCCTN: configs/resources/audio/3dB/Anechoic/p286_172_1_ISO.wav
              OMVDR: configs/resources/audio/3dB/Anechoic/p286_172_1_omvdr.wav
              GOMVDR: configs/resources/audio/3dB/Anechoic/p286_172_1_mc_OMVDR.wav
              GFCIM: configs/resources/audio/3dB/Anechoic/p286_172_1_mc_FCIM.wav
      -
        - type: mushra
          id: test_3db_reverb
          name: Listening Test
          content: Please listen to the reference. Then, grade each of the stimuli below by assessing how they compare to the reference. 
          showWaveform: true
          enableLooping: true 
          reference: configs/resources/audio/3dB/Reverb/p286_209_1_mc_rb.wav
          createAnchor35: true
          createAnchor70: true
          randomize: true
          showConditionNames: false
          stimuli: 
              MBCCTN: configs/resources/audio/3dB/Reverb/p286_209_1_ISO_RB.wav
              OMVDR: configs/resources/audio/3dB/Reverb/p286_209_1_omvdr.wav
              GOMVDR: configs/resources/audio/3dB/Reverb/p286_209_1_OMVDR_RB.wav
              GFCIM: configs/resources/audio/3dB/Reverb/p286_209_1_rb_mc_FCIM_RB.wav
      -
        - type: mushra
          id: test_6db_anechoic
          name: Listening Test
          content: Please listen to the reference. Then, grade each of the stimuli below by assessing how they compare to the reference. 
          showWaveform: true
          enableLooping: true 
          reference: configs/resources/audio/6dB/Anechoic/p286_101_1_6dB.wav
          createAnchor35: true
          createAnchor70: true
          randomize: true
          showConditionNames: false
          stimuli: 
              MBCCTN: configs/resources/audio/6dB/Anechoic/p286_101_1_MBCCTN_40E.wav
              OMVDR: configs/resources/audio/6dB/Anechoic/p286_101_1_OMVDR.wav
              GOMVDR: configs/resources/audio/6dB/Anechoic/p286_101_1_17M.wav
              GFCIM: configs/resources/audio/6dB/Anechoic/p286_101_1_6dB_GFCIM.wav
      -
        - type: mushra
          id: test_6db_reverb
          name: Listening Test
          content: Please listen to the reference. Then, grade each of the stimuli below by assessing how they compare to the reference. 
          showWaveform: true
          enableLooping: true 
          reference: configs/resources/audio/6dB/Reverb/p282_330_0_rb.wav
          createAnchor35: true
          createAnchor70: true
          randomize: true
          showConditionNames: false
          stimuli: 
              MBCCTN: configs/resources/audio/6dB/Reverb/p282_330_0_MBCCTN_RVRB.wav
              OMVDR: configs/resources/audio/6dB/Reverb/p282_330_0_OMVDR_RVRB.wav
              GOMVDR: configs/resources/audio/6dB/Reverb/p282_330_0_17M_RVRB.wav
              GFCIM: configs/resources/audio/6dB/Reverb/p282_330_0_rb_GFCIM.wav
      -
        - type: mushra
          id: test_9db_anechoic
          name: Listening Test
          content: Please listen to the reference. Then, grade each of the stimuli below by assessing how they compare to the reference. 
          showWaveform: true
          enableLooping: true 
          reference: configs/resources/audio/9dB/Anechoic/p286_235_1_9dB.wav
          createAnchor35: true
          createAnchor70: true
          randomize: true
          showConditionNames: false
          stimuli: 
              MBCCTN: configs/resources/audio/9dB/Anechoic/p286_235_1_MBCCTN_40E.wav
              OMVDR: configs/resources/audio/9dB/Anechoic/p286_235_1_OMVDR.wav
              GOMVDR: configs/resources/audio/9dB/Anechoic/p286_235_1_17M.wav
              GFCIM: configs/resources/audio/9dB/Anechoic/p286_235_1_9dB_GFCIM.wav
      -
        - type: mushra
          id: test_9db_reverb
          name: Listening Test
          content: Please listen to the reference. Then, grade each of the stimuli below by assessing how they compare to the reference. 
          showWaveform: true
          enableLooping: true 
          reference: configs/resources/audio/9dB/Reverb/p286_373_1_rb.wav
          createAnchor35: true
          createAnchor70: true
          randomize: true
          showConditionNames: false
          stimuli: 
              MBCCTN: configs/resources/audio/9dB/Reverb/p286_373_1_MBCCTN_RVRB.wav
              OMVDR: configs/resources/audio/9dB/Reverb/p286_373_1_OMVDR_RVRB.wav
              GOMVDR: configs/resources/audio/9dB/Reverb/p286_373_1_17M_RVRB.wav
              GFCIM: configs/resources/audio/9dB/Reverb/p286_373_1_rb_GFCIM.wav
      -
        - type: mushra
          id: test_12db_anechoic
          name: Listening Test
          content: Please listen to the reference. Then, grade each of the stimuli below by assessing how they compare to the reference. 
          showWaveform: true
          enableLooping: true 
          reference: configs/resources/audio/12dB/Anechoic/p287_151_1_12dB.wav
          createAnchor35: true
          createAnchor70: true
          randomize: true
          showConditionNames: false
          stimuli: 
              MBCCTN: configs/resources/audio/12dB/Anechoic/p287_151_1_MBCCTN_40E.wav
              OMVDR: configs/resources/audio/12dB/Anechoic/p287_151_1_OMVDR.wav
              GOMVDR: configs/resources/audio/12dB/Anechoic/p287_151_1_17M.wav
              GFCIM: configs/resources/audio/12dB/Anechoic/p287_151_1_12dB_GFCIM.wav
      -
        - type: mushra
          id: test_12db_reverb
          name: Listening Test
          content: Please listen to the reference. Then, grade each of the stimuli below by assessing how they compare to the reference. 
          showWaveform: true
          enableLooping: true 
          reference: configs/resources/audio/12dB/Reverb/p286_389_0_rb.wav
          createAnchor35: true
          createAnchor70: true
          randomize: true
          showConditionNames: false
          stimuli: 
              MBCCTN: configs/resources/audio/12dB/Reverb/p286_389_0_MBCCTN_RVRB.wav
              OMVDR: configs/resources/audio/12dB/Reverb/p286_389_0_OMVDR_RVRB.wav
              GOMVDR: configs/resources/audio/12dB/Reverb/p286_389_0_rb_GFCIM.wav
              GFCIM: configs/resources/audio/12dB/Reverb/p286_389_0_17M_RVRB.wav
      -
        - type: mushra
          id: test_15db_anechoic
          name: Listening Test
          content: Please listen to the reference. Then, grade each of the stimuli below by assessing how they compare to the reference. 
          showWaveform: true
          enableLooping: true 
          reference: configs/resources/audio/15dB/Anechoic/sp16_0_15dB.wav
          createAnchor35: true
          createAnchor70: true
          randomize: true
          showConditionNames: false
          stimuli: 
              MBCCTN: configs/resources/audio/15dB/Anechoic/sp16_0_MBCCTN_40E.wav
              OMVDR: configs/resources/audio/15dB/Anechoic/sp16_0_OMVDR.wav
              GOMVDR: configs/resources/audio/15dB/Anechoic/sp16_0_17M.wav
              GFCIM: configs/resources/audio/15dB/Anechoic/sp16_0_15dB_GFCIM.wav
      -
        - type: mushra
          id: test_15db_reverb
          name: Listening Test
          content: Please listen to the reference. Then, grade each of the stimuli below by assessing how they compare to the reference. 
          showWaveform: true
          enableLooping: true 
          reference: configs/resources/audio/15dB/Reverb/p287_180_0_rb.wav
          createAnchor35: true
          createAnchor70: true
          randomize: true
          showConditionNames: false
          stimuli: 
              MBCCTN: configs/resources/audio/15dB/Reverb/p287_180_0_MBCCTN_RVRB.wav
              OMVDR: configs/resources/audio/15dB/Reverb/p287_180_0_OMVDR_RVRB.wav
              GOMVDR: configs/resources/audio/15dB/Reverb/p287_180_0_17M_RVRB.wav
              GFCIM: configs/resources/audio/15dB/Reverb/p287_180_0_rb_GFCIM.wav

    - type: finish
      name: Finish
      content: This is the end of the test. Please fill out your name below.
      showResults: false
      writeResults: true
      questionnaire:
          - type: text
            label: Name
            name: Name
#configs/resources/audio/m3dB/Anechoic/p278_082_0_OMVDR.wav  